version: "3.8"
services:
  backend:
    image: "mauricio17/springboot-react-course:18.11.2022.15.59.37"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev