version: "3.8"
services:
  backend:
    image: "mauricio17/springboot-react-course:25.11.2022.14.33.46"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev